"""
Application Constants
"""

# Application Info
APP_NAME = "GestureControl Pro"
APP_VERSION = "1.0.0"
APP_AUTHOR = "GestureControl Team"

# Paths
DEFAULT_DATASET_PATH = "datasets"
DEFAULT_MODELS_PATH = "models/saved_models"
DEFAULT_CONFIG_PATH = "config"
DEFAULT_LOGS_PATH = "logs"

# Camera
DEFAULT_CAMERA_INDEX = 0
DEFAULT_RESOLUTION = (640, 480)
DEFAULT_FPS = 30
MAX_CAMERAS = 5

# Recognition
DEFAULT_CONFIDENCE_THRESHOLD = 0.85
DEFAULT_COOLDOWN_MS = 500
MIN_CONFIDENCE = 0.5

# Training
DEFAULT_EPOCHS = 50
DEFAULT_BATCH_SIZE = 32
DEFAULT_LEARNING_RATE = 0.001
MIN_IMAGES_PER_GESTURE = 50

# Hand Detection
NUM_LANDMARKS = 21
LANDMARK_DIMENSIONS = 3

# UI
THUMBNAIL_SIZE = 100
MAX_HISTORY_ITEMS = 100
